/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PROGRAM = 1,
  anon_sym_END_PROGRAM = 2,
  anon_sym_VAR = 3,
  anon_sym_END_VAR = 4,
  anon_sym_COLON = 5,
  anon_sym_SEMI = 6,
  anon_sym_COLON_EQ = 7,
  sym_identifier = 8,
  anon_sym_BOOL = 9,
  anon_sym_INT = 10,
  anon_sym_REAL = 11,
  anon_sym_DINT = 12,
  sym_number = 13,
  sym_source_file = 14,
  sym__definition = 15,
  sym_program_declaration = 16,
  sym_variable_block = 17,
  sym_variable_declaration = 18,
  sym_statement = 19,
  sym_assignment = 20,
  sym_type_identifier = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_program_declaration_repeat1 = 23,
  aux_sym_variable_block_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PROGRAM] = "PROGRAM",
  [anon_sym_END_PROGRAM] = "END_PROGRAM",
  [anon_sym_VAR] = "VAR",
  [anon_sym_END_VAR] = "END_VAR",
  [anon_sym_COLON] = ":",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON_EQ] = ":=",
  [sym_identifier] = "identifier",
  [anon_sym_BOOL] = "BOOL",
  [anon_sym_INT] = "INT",
  [anon_sym_REAL] = "REAL",
  [anon_sym_DINT] = "DINT",
  [sym_number] = "number",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_program_declaration] = "program_declaration",
  [sym_variable_block] = "variable_block",
  [sym_variable_declaration] = "variable_declaration",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym_type_identifier] = "type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_declaration_repeat1] = "program_declaration_repeat1",
  [aux_sym_variable_block_repeat1] = "variable_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PROGRAM] = anon_sym_PROGRAM,
  [anon_sym_END_PROGRAM] = anon_sym_END_PROGRAM,
  [anon_sym_VAR] = anon_sym_VAR,
  [anon_sym_END_VAR] = anon_sym_END_VAR,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_identifier] = sym_identifier,
  [anon_sym_BOOL] = anon_sym_BOOL,
  [anon_sym_INT] = anon_sym_INT,
  [anon_sym_REAL] = anon_sym_REAL,
  [anon_sym_DINT] = anon_sym_DINT,
  [sym_number] = sym_number,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_program_declaration] = sym_program_declaration,
  [sym_variable_block] = sym_variable_block,
  [sym_variable_declaration] = sym_variable_declaration,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym_type_identifier] = sym_type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_declaration_repeat1] = aux_sym_program_declaration_repeat1,
  [aux_sym_variable_block_repeat1] = aux_sym_variable_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_PROGRAM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_VAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END_VAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BOOL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_INT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DINT] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_program_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_block] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(37);
      ADVANCE_MAP(
        ':', 46,
        ';', 47,
        'B', 24,
        'D', 14,
        'E', 19,
        'I', 20,
        'P', 29,
        'R', 10,
        'V', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == 'E') ADVANCE(56);
      if (lookahead == 'V') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == 'E') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'D') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(6);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 12:
      if (lookahead == 'G') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'G') ADVANCE(31);
      END_STATE();
    case 14:
      if (lookahead == 'I') ADVANCE(21);
      END_STATE();
    case 15:
      if (lookahead == 'L') ADVANCE(68);
      END_STATE();
    case 16:
      if (lookahead == 'L') ADVANCE(70);
      END_STATE();
    case 17:
      if (lookahead == 'M') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'M') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'N') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'N') ADVANCE(33);
      END_STATE();
    case 21:
      if (lookahead == 'N') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'O') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(12);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(22);
      END_STATE();
    case 25:
      if (lookahead == 'O') ADVANCE(13);
      END_STATE();
    case 26:
      if (lookahead == 'P') ADVANCE(32);
      if (lookahead == 'V') ADVANCE(8);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 'R') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'R') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(4);
      END_STATE();
    case 31:
      if (lookahead == 'R') ADVANCE(7);
      END_STATE();
    case 32:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(69);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(71);
      END_STATE();
    case 35:
      if (lookahead == '_') ADVANCE(26);
      END_STATE();
    case 36:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(36);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PROGRAM);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_END_PROGRAM);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_END_PROGRAM);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_VAR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_VAR);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_END_VAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_END_VAR);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'G') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'V') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_BOOL);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_INT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_REAL);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DINT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 36},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PROGRAM] = ACTIONS(1),
    [anon_sym_END_PROGRAM] = ACTIONS(1),
    [anon_sym_VAR] = ACTIONS(1),
    [anon_sym_END_VAR] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_BOOL] = ACTIONS(1),
    [anon_sym_INT] = ACTIONS(1),
    [anon_sym_REAL] = ACTIONS(1),
    [anon_sym_DINT] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym__definition] = STATE(4),
    [sym_program_declaration] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PROGRAM] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      anon_sym_END_PROGRAM,
    ACTIONS(9), 1,
      anon_sym_VAR,
    ACTIONS(11), 1,
      sym_identifier,
    STATE(5), 1,
      sym_variable_block,
    STATE(23), 1,
      sym_assignment,
    STATE(6), 2,
      sym_statement,
      aux_sym_program_declaration_repeat1,
  [20] = 3,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      anon_sym_PROGRAM,
    STATE(3), 3,
      sym__definition,
      sym_program_declaration,
      aux_sym_source_file_repeat1,
  [32] = 3,
    ACTIONS(5), 1,
      anon_sym_PROGRAM,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    STATE(3), 3,
      sym__definition,
      sym_program_declaration,
      aux_sym_source_file_repeat1,
  [44] = 4,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(20), 1,
      anon_sym_END_PROGRAM,
    STATE(23), 1,
      sym_assignment,
    STATE(7), 2,
      sym_statement,
      aux_sym_program_declaration_repeat1,
  [58] = 4,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(20), 1,
      anon_sym_END_PROGRAM,
    STATE(23), 1,
      sym_assignment,
    STATE(8), 2,
      sym_statement,
      aux_sym_program_declaration_repeat1,
  [72] = 4,
    ACTIONS(11), 1,
      sym_identifier,
    ACTIONS(22), 1,
      anon_sym_END_PROGRAM,
    STATE(23), 1,
      sym_assignment,
    STATE(8), 2,
      sym_statement,
      aux_sym_program_declaration_repeat1,
  [86] = 4,
    ACTIONS(24), 1,
      anon_sym_END_PROGRAM,
    ACTIONS(26), 1,
      sym_identifier,
    STATE(23), 1,
      sym_assignment,
    STATE(8), 2,
      sym_statement,
      aux_sym_program_declaration_repeat1,
  [100] = 2,
    STATE(28), 1,
      sym_type_identifier,
    ACTIONS(29), 4,
      anon_sym_BOOL,
      anon_sym_INT,
      anon_sym_REAL,
      anon_sym_DINT,
  [110] = 3,
    ACTIONS(31), 1,
      anon_sym_END_VAR,
    ACTIONS(33), 1,
      sym_identifier,
    STATE(12), 2,
      sym_variable_declaration,
      aux_sym_variable_block_repeat1,
  [121] = 3,
    ACTIONS(35), 1,
      anon_sym_END_VAR,
    ACTIONS(37), 1,
      sym_identifier,
    STATE(11), 2,
      sym_variable_declaration,
      aux_sym_variable_block_repeat1,
  [132] = 3,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(40), 1,
      anon_sym_END_VAR,
    STATE(11), 2,
      sym_variable_declaration,
      aux_sym_variable_block_repeat1,
  [143] = 1,
    ACTIONS(42), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [148] = 1,
    ACTIONS(44), 2,
      anon_sym_END_PROGRAM,
      sym_identifier,
  [153] = 1,
    ACTIONS(46), 2,
      anon_sym_END_PROGRAM,
      sym_identifier,
  [158] = 1,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [163] = 1,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      anon_sym_PROGRAM,
  [168] = 1,
    ACTIONS(52), 2,
      anon_sym_END_PROGRAM,
      sym_identifier,
  [173] = 1,
    ACTIONS(54), 2,
      anon_sym_END_VAR,
      sym_identifier,
  [178] = 1,
    ACTIONS(56), 1,
      sym_identifier,
  [182] = 1,
    ACTIONS(58), 1,
      anon_sym_COLON_EQ,
  [186] = 1,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
  [190] = 1,
    ACTIONS(62), 1,
      anon_sym_SEMI,
  [194] = 1,
    ACTIONS(64), 1,
      sym_number,
  [198] = 1,
    ACTIONS(66), 1,
      anon_sym_SEMI,
  [202] = 1,
    ACTIONS(68), 1,
      anon_sym_COLON,
  [206] = 1,
    ACTIONS(70), 1,
      anon_sym_SEMI,
  [210] = 1,
    ACTIONS(72), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 32,
  [SMALL_STATE(5)] = 44,
  [SMALL_STATE(6)] = 58,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 86,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 110,
  [SMALL_STATE(11)] = 121,
  [SMALL_STATE(12)] = 132,
  [SMALL_STATE(13)] = 143,
  [SMALL_STATE(14)] = 148,
  [SMALL_STATE(15)] = 153,
  [SMALL_STATE(16)] = 158,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 168,
  [SMALL_STATE(19)] = 173,
  [SMALL_STATE(20)] = 178,
  [SMALL_STATE(21)] = 182,
  [SMALL_STATE(22)] = 186,
  [SMALL_STATE(23)] = 190,
  [SMALL_STATE(24)] = 194,
  [SMALL_STATE(25)] = 198,
  [SMALL_STATE(26)] = 202,
  [SMALL_STATE(27)] = 206,
  [SMALL_STATE(28)] = 210,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [22] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_declaration_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_block_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_block_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_declaration, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_block, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_declaration, 5, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_declaration, 4, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_block, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_declaration, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [60] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_st(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "st",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
